#!/usr/bin/env python2

from pandocfilters import toJSONFilter, Math, Str, Space


idioms = set(['Eq.~', 'Eqs.~', 'Equation~', 'Equations~',
              'Fig.~', 'Figs.~', 'Figure~', 'Figures~',
              'Ref.~', 'Refs.~', 'Reference~', 'References~',
              'Table~', 'Tables~',
              'and~'])


def eqref(key, value, fmt, meta):
    # replace idiomatic tilde with space
    if key == 'Str':
        if value in idioms:
            return [Str(value[:-1]), Space()]

    # wrap \ref and \eqref in Math()
    elif key == 'RawInline' and value[0] == 'tex':
        if value[1].startswith(r'\ref') or value[1].startswith(r'\eqref'):
            return Math(dict(t='InlineMath'), value[1])


if __name__ == '__main__':
    toJSONFilter(eqref)
